doc-warnings: true
test-warnings: false
strictness: veryhigh
max-line-length: 120
autodetect: true
ignore-paths:
  - docs
ignore-patterns:
  - ^example/doc_.*\.py$
  - (^|/)docs(/|$)
python-targets:
  - 3

