version: 2

# The Docker image used for building the docs.
build:
  image: stable

python:
  version: 3.7
  install:
    - requirements: ./pre-requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - all
