
line-length = 100
target-version = "py39"

select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # Unused noqa directive
    "RUF100",
    # isort
    "I",
]

# Handled by black:
# E501: Line too long
#
# Currently not passing errors:
# E402 Module level import not at top of file
# F541 f-string without any placeholders
ignore = ["E501", "E402", "F541"]

extend-exclude = [
    "docs",
    "parsec/core/gui/_resources_rc.py",
    "parsec/core/gui/ui/",
    "misc/bench.py",
]

[isort]
known-first-party = ["parsec", "antivirus_connector", "resana_secure"]
