[package]
name = "parsec_serialization_format"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
miniserde = "0.1"
