[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "tgbverifier"
version = "1.0.0"
description = "Checks TheGreenBow DLL conformity"
authors = [{ name = "Scille SAS" }]
